steps:
  - name: "gcr.io/cloud-builders/npm"
    args: ["install"]
    dir: "function/dir/from/repo/root"
  - name: "gcr.io/cloud-builders/npm"
    args: ["test"]
    dir: "function/dir/from/repo/root"
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "functions",
        "deploy",
        "annotate-video",
        "annotate-video",
        "--runtime",
        "nodejs18",
        "--entry-point",
        "annotateVideo",
      ]
    dir: "function/dir/from/repo/root"
