name: Typecheck

on:
  push:
    branches: ["*"]

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
    #   - name: Install service upload dependencies
    #     working-directory: ./service-upload
    #     run: npm install
    #   - name: Typecheck
    #     run: npm run typecheck
    #  - name: Install annotate video dependencies
    #     working-directory: ./cloud-functions/annotate-video
    #     run: npm install
    #   - name: Typecheck
        run: npm run typecheck
